Allow PHP 8
contao/mobile-page-layout-bundle pull request #5
Opened 2020-09-11 10:30 UTC by leofeyer

I have checked the code with https://github.com/PHPCompatibility/PHPCompatibility and updated the Composer requirement. Is there anything else to do?

2020-09-11 10:59 UTC, ausi commented
Did you check if the unit tests run through?

And we need to agree on `^7.1 || ^8.0` vs. `>=7.1` before we can merge this.

2020-11-19 20:58 UTC, Toflar requested changes
This should be adjusted to `^7.1 | ^8.0`.

2020-11-27 09:28 UTC, leofeyer commented
Done.

2020-11-27 09:40 UTC, Toflar approved these changes

2020-11-27 09:44 UTC, merged